rails_chat/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#login"
  post "create_session", to: "rooms#create_session", as: "create_session"
  delete "destroy_session", to: "rooms#destroy_session", as: "destroy_session"

  get "/rooms", to: "rooms#index", as: "rooms"
  get "/rooms/:id", to: "rooms#show", as: "room"
end

rails_chat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_chat/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :ensure_login, except: [:login, :create_session]

  helper_method :current_user

  def login
    redirect_to rooms_path if cookies.encrypted[:name].present?
  end

  def create_session
    cookies.encrypted[:name] = params[:name]

    redirect_to rooms_path
  end

  def destroy_session
    cookies.encrypted[:name] = nil

    redirect_to root_path
  end

  def index
  end

  def show
    @room_id = params[:id]
  end

  private
    def current_user
      @current_user ||= cookies.encrypted[:name]
    end

    def ensure_login
      redirect_to root_path if current_user.blank?
    end
end

rails_chat/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_chat/app/helpers/rooms_helper.rb
module RoomsHelper
end

rails_chat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat Room</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

rails_chat/app/views/rooms/index.html.erb
<div class="mb-3">
  <%= form_with url: destroy_session_path, method: :delete do |form| %>
    <% form.submit "Logout", class: "button is-dark" %>
  <% end %>
</div>

<div class="columns">
  <% [1, 2, 3, 4, "forbidden_room"].each do |i| %>
    <div class="column">
      <div class="card">
        <header class="card-header">
          <div class="card-header-title">
            Room <%= i %>
          </div>
        </header>
        <footer class="card-footer">
          <%= link_to "Entry Room #{i}", room_path(i), class: "card-footer-item button is-dark" %>
        </footer>
      </div>
    </div>
  <% end %>
</div>

rails_chat/app/views/rooms/login.html.erb
<div class="columns">
  <div class="column is-three-fifths is-offset-one-fifth box">
    <%= form_with url: create_session_path, id: "chat-form", data: { "room-id": "fake" } do |form| %>
      <div class="field">
        <%= form.label :name, "Name", class: "label" %>
        <div class="control">
          <%= form.text_field :name, class: "input" %>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <%= form.submit "Sign in", class: "button is-dark"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

rails_chat/app/views/rooms/show.html.erb
<div class="box">
  <div id="messages" class="box" style="min-height:300px">
  </div>
  <div class="box">
    <form id="chat-form" data-room-id="<%= @room_id %>">
      <div class="field">
        <div class="control">
          <textarea class="textarea" placeholder="message"></textarea>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <button class="button is-dark">Send</button>
        </div>
      </div>
    </form>

    <hr>

    <div class="field mt-5">
      <legend>Client initiated unsubscribing channel</legend>
      <div class="control">
        <button class="button is-dark" id="unsubscribe-btn">
          Unsubscribe
        </button>
      </div>
    </div>

    <div class="field mt-5">
      <legend>Server initiated unsubscribing channel</legend>
      <div class="control">
        <button class="button is-dark" id="stop-stream-btn">
          Stop Stream (subscription)
        </button>
      </div>
    </div>

    <form class="mt-5" id="kick-form">
      <legend>Terminate one remote connection.</legend>
      <div class="field has-addons">
        <div class="control">
          <input class="input" type="text" placeholder="Input a name">
        </div>
        <div class="control">
          <button class="button is-dark">
            Kick!
          </button>
        </div>
      </div>
    </form>
  <div>
</div>